### ISSUE TITLE
PackagesNotFoundError: - openalea.phenomenal

### ISSUE THREAD

**Issue by Illustratien** [openalea/phenotrack3d#5]
Hi,
Romain suggested me to try this package. I would be appreicated if you can help me with the installation.

I have tried to create the conda environment based on 
`conda create -n phenotrack -c conda-forge -c openalea3 openalea.phenomenal skan=0.9`
And I got

> `Collecting package metadata (current_repodata.json): done
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - openalea.phenomenal
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge/win-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://conda.anaconda.org/openalea3/win-64
>   - https://conda.anaconda.org/openalea3/noarch
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.`

Any thought?
Thank you in advance.
Best,
Tien-Cheng

**Comment by pradal** [comment]
Yes.
Try
   conda create -n phenotrack -c conda-forge -c openalea openalea.phenomenal skan=0.9

**Comment by Illustratien** [comment]
Thanks Pradal! 
It works.
